name: Artifact Demo

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Artifact File
        run: echo "Build completed successfully" > build.txt

      - name: Show File
